##用户
DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `GMT_CREATE` DATETIME,
  `GMT_MODIFIED` DATETIME,
  `STATUS` INT,
  `ACCOUNT` VARCHAR(64) COMMENT '支付宝帐号',
   `COOKIE_ID`  VARCHAR(64),
   `MEMO` VARCHAR(1024),	
   PRIMARY KEY (`ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;

##
DROP TABLE IF EXISTS `USERANDPRO`;
CREATE TABLE `USERANDPRO` (
   `ID` INT NOT NULL AUTO_INCREMENT,
   `GMT_CREATE` DATETIME,
   `GMT_MODIFIED` DATETIME,
   `STATUS` INT,
    `IDENTITY`  VARCHAR(16),
    `USER_ID` INT,
    `ALIPAY_STATUS` VARCHAR(8),
    `PRODUCT_URL`  VARCHAR(256),
    `IP`  VARCHAR(32),
     `PRICE` INT,
     PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
